# Generated by Django 3.1 on 2020-12-24 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myweb_main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('create_date', models.DateTimeField(verbose_name='작성일시')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '질문에대한답변',
                'verbose_name_plural': '질문에대한답변',
                'db_table': '질문에대한답변',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('create_date', models.DateTimeField(verbose_name='작성일시')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('voter', models.ManyToManyField(related_name='QVoter', to=settings.AUTH_USER_MODEL, verbose_name='추천')),
            ],
            options={
                'verbose_name': '질문게시판',
                'verbose_name_plural': '질문게시판',
                'db_table': '질문게시판',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('create_date', models.DateTimeField(verbose_name='작성일시')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('voter', models.ManyToManyField(related_name='NoVoter', to=settings.AUTH_USER_MODEL, verbose_name='추천')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'db_table': '공지사항',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('create_date', models.DateTimeField(verbose_name='작성일시')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=myweb_main.models.FilePath, verbose_name='파일')),
                ('file_subject', models.CharField(max_length=64, null=True, verbose_name='파일제목')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('voter', models.ManyToManyField(related_name='MoVoter', to=settings.AUTH_USER_MODEL, verbose_name='추천')),
            ],
            options={
                'verbose_name': '영화게시판',
                'verbose_name_plural': '영화게시판',
                'db_table': '영화게시판',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('create_date', models.DateTimeField(verbose_name='작성일시')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=myweb_main.models.FilePath, verbose_name='파일')),
                ('file_subject', models.CharField(max_length=64, null=True, verbose_name='파일제목')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('voter', models.ManyToManyField(related_name='GVoter', to=settings.AUTH_USER_MODEL, verbose_name='추천')),
            ],
            options={
                'verbose_name': '게임게시판',
                'verbose_name_plural': '게임게시판',
                'db_table': '게임게시판',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('create_date', models.DateTimeField(verbose_name='작성일시')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myweb_main.answer', verbose_name='답변댓글')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myweb_main.game', verbose_name='게임댓글')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myweb_main.movie', verbose_name='영화댓글')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myweb_main.question', verbose_name='질문댓글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': '댓글',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb_main.question', verbose_name='질문아이디'),
        ),
        migrations.AddField(
            model_name='answer',
            name='voter',
            field=models.ManyToManyField(related_name='AVoter', to=settings.AUTH_USER_MODEL, verbose_name='추천'),
        ),
    ]
