# Generated by Django 3.1.7 on 2021-03-29 06:27

from django.db import migrations, models
import myweb_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb_main', '0002_auto_20210223_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='file_subject',
            field=models.CharField(max_length=64, null=True, verbose_name='파일제목'),
        ),
        migrations.AddField(
            model_name='question',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=myweb_main.models.FilePath, verbose_name='파일'),
        ),
    ]
