# Generated by Django 3.1.7 on 2021-03-30 07:08

from django.db import migrations, models
import myweb_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb_main', '0003_auto_20210329_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file_subject',
            field=models.CharField(max_length=64, null=True, verbose_name='파일제목'),
        ),
        migrations.AddField(
            model_name='notice',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=myweb_main.models.FilePath, verbose_name='파일'),
        ),
    ]
