# Generated by Django 3.1.7 on 2021-04-22 08:20

from django.db import migrations, models
import login.Validators


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210223_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=20, validators=[login.Validators.NameValidate], verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=11, validators=[login.Validators.PhoneValidate], verbose_name='휴대폰번호'),
        ),
    ]
