# Generated by Django 3.1.7 on 2021-04-26 05:38

from django.db import migrations, models
import login.Validators


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210426_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[login.Validators.PhoneValidate], verbose_name='전화번호'),
        ),
    ]
