# Generated by Django 3.1.7 on 2021-04-26 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login.Validators


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_socialuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[login.Validators.NameValidate], verbose_name='이름'),
        ),
    ]
