# Generated by Django 3.1.7 on 2021-04-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210426_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='name',
        ),
    ]
