# Generated by Django 3.1.7 on 2021-04-26 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login.Validators


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_socialuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='user',
        ),
        migrations.AddField(
            model_name='socialuser',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[login.Validators.SignupValidate], verbose_name='아이디'),
        ),
    ]
