# Generated by Django 3.1.7 on 2021-04-26 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login.Validators


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20210426_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[login.Validators.NameValidate], verbose_name='이름'),
        ),
    ]
