# Generated by Django 3.1.7 on 2021-04-26 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20210426_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
