# Generated by Django 3.1.7 on 2021-04-26 08:11

from django.db import migrations, models
import login.Validators


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20210426_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='name2',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[login.Validators.NameValidate], verbose_name='이름2'),
        ),
    ]
