# Generated by Django 3.1.7 on 2021-04-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_socialuser_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='name2',
        ),
    ]
