# Generated by Django 3.1.7 on 2021-04-26 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_socialuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='소셜사용자'),
        ),
    ]
